#resolver: nightly-2022-12-17
resolver: lts-18.9

packages:
- .
- ../fractalstream-core

extra-deps:
- git: https://github.com/llvm-hs/llvm-hs.git
  commit: 423220bffac4990d019fc088c46c5f25310d5a33
  subdirs:
    - llvm-hs
    - llvm-hs-pure
- megaparsec-9.2.0@sha256:0c272aa13b9f663dbd7b74ef81e9b1f9f05cafde50f5362ce87ffd4913046e0b,3213
- git: https://github.com/mgrabmueller/disassembler
  commit: 15a15db1fba50fd0ce52f26f43550fbad5529bf8

allow-newer: true

# Override default flag values for local packages and extra-deps
flags:
  llvm-hs:
    shared-llvm: true

ghc-options:
  llvm-hs:
    -optcxx=-std=c++17
