resolver: lts-18.9

packages:
- .
- ../fractalstream-core
- ../fractalstream-backend-llvm

extra-deps:
- cabal-macosx-0.2.4.2@sha256:6794dab50ca2a062b9c54455442ccc3d9d9ffa6dbdb81940597329e3b377436b,3045
- megaparsec-9.1.0@sha256:f2ef8a08cc1e3fa6628965732f588e07e886a01f8267310404e31072fa9e802b,3238
- git: https://github.com/llvm-hs/llvm-hs.git
  commit: d348dcff95f3f1c17289b5ba0a173397d0e005fc
  subdirs:
    - llvm-hs
    - llvm-hs-pure

- git: https://github.com/matt-noonan/wxHaskell.git
  commit: f4bab8e081bd45795d68a9ade089ee36023632c8
  subdirs:
      - wx
      - wxcore
      - wxc
      - wxdirect

# Override default flag values for local packages and extra-deps
flags:
  llvm-hs:
    shared-llvm: true

ghc-options:
  llvm-hs:
    -optcxx=-std=c++17

extra-lib-dirs:
- /usr/local/Cellar/libffi/3.4.4/lib/
