cabal-version:       3.0
name:                fractalstream-core
version:             2.0.0.0
synopsis:            Tool for dynamical systems research.
description:         Dynamical system visualization
license:             BSD-3-Clause
license-file:        LICENSE
author:              Matt Noonan
maintainer:          matt.noonan@gmail.com
copyright:           2021, Matt Noonan
category:            Math
build-type:          Simple

common FractalStream-common
  ghc-options:         -Wall -Werror -O2
  -- This is basically the list of extensions from
  -- https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/
  -- with a few minor additions like ViewPatterns.
  -- I also switch on RecordWildCards because I like it: it lets you bring
  -- all fields of a record into scope, giving some of the flavor of an OOP
  -- language with member variables automatically in scope of object methods.
  default-extensions:  ApplicativeDo
                     , BangPatterns
                     , ConstraintKinds
                     , DataKinds
                     , DefaultSignatures
                     , DeriveFoldable
                     , DeriveFunctor
                     , DeriveGeneric
                     , DeriveLift
                     , DeriveTraversable
                     , DerivingStrategies
                     , EmptyCase
                     , ExistentialQuantification
                     , FlexibleContexts
                     , FlexibleInstances
                     , FunctionalDependencies
                     , GADTs
                     , GeneralizedNewtypeDeriving
                     , InstanceSigs
                     , KindSignatures
                     , LambdaCase
                     , MultiParamTypeClasses
                     , MultiWayIf
                     , NamedFieldPuns
                     , PatternSynonyms
                     , RankNTypes
                     , RecordWildCards
                     , RequiredTypeArguments
                     , ScopedTypeVariables
                     , StandaloneDeriving
                     , TupleSections
                     , TypeApplications
                     , TypeFamilies
                     , TypeFamilyDependencies
                     , TypeOperators
                     , ViewPatterns
  default-language:    Haskell2010

library
  import: FractalStream-common
  exposed-modules:
                       FractalStream.Prelude
                       FractalStream.Metadata

                       Actor.Tool
                       Actor.Configuration
                       Actor.Ensemble
                       Actor.Layout
                       Actor.UI
                       Actor.Viewer
                       Actor.Viewer.Complex
                       Actor.Event

                       Event

                       Task.Concurrent
                       Task.Block

                       Language.Code
                       Language.Code.Simulator
                       Language.Code.InterpretIO
                       Language.Code.Parser
                       Language.Code.Typecheck
                       Language.Type
                       Language.Environment
                       Language.Value
                       Language.Value.Evaluator
                       Language.Value.Parser
                       Language.Value.Typecheck
                       Language.Value.Transform
                       Language.Draw
                       Language.Parser
                       Language.Typecheck
                       Language.Parser.Tokenizer
                       Language.Parser.SourceRange

                       Project

                       Data.Indexed.Functor
                       Data.Planar
                       Data.Color
                       Data.Recursive
                       Data.DynamicValue
                       Data.Codec

  c-sources: src/FractalStream/find_jemalloc.c

  build-depends:       base >=4.8 && <5,
                       random,
                       aeson,
                       yaml,
                       array,
                       async,
                       containers,
                       constraints,
                       megaparsec >= 9.1,
                       parser-combinators,
                       mtl,
                       monad-parallel,
                       monad-par,
                       monad-par-extras,
                       numeric-extras,
                       text,
                       time,
                       bytestring,
                       vector,
                       first-class-families,
                       bifunctors,
                       Earley,
                       include-file,
                       utf8-string,
                       githash,
  hs-source-dirs:      src

test-suite spec
  import: FractalStream-common
  hs-source-dirs: test
  type: exitcode-stdio-1.0
  main-is: Spec.hs
  build-depends:      base >=4.8 && <5
                    , fractalstream-core
                    , hspec
                    , first-class-families
                    , raw-strings-qq
                    , mtl
                    , containers
  other-modules:      Data.Indexed.FunctorSpec
                    , Language.Value.EvaluatorSpec
                    , Language.Value.ParserSpec
                    , Language.Code.ParserSpec
                    , Language.Effect.ListSpec
  build-tool-depends: hspec-discover:hspec-discover == 2.*
