name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: |
        sudo apt install libffi-dev
        sudo apt install llvm-dev
        sudo apt install libwxgtk3.0-gtk3-dev
        sudo apt install libwxgtk-media3.0-gtk3-dev
    - name: Build
      run: |
        cd fractalstream-ui-wx
        stack build
    - name: Run tests
      run: stack test
