name: macOS build

on: [push]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: |
        brew install haskell-stack
        brew install libffi
        brew install llvm-hs/llvm/llvm-12
        brew install wxwidgets
    - name: Build
      run: |
        cd fractalstream-ui-wx
        stack build
