name: macOS build

on: [push]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: |
        brew install haskell-stack
        brew install libffi
        brew install llvm-hs/llvm/llvm-12
        echo WX `which wx-config`
        brew install wxwidgets@3.0
        ln -s `which wx-config-3.0` $(dirname `which wx-config-3.0`)/wx-config
        ln -s `which wxrc-3.0` $(dirname `which wxrc-3.0`)/wxrc
        ln -s /usr/local/Cellar/wxwidgets/3.2.2.1_1/lib/wx /usr/local/lib/wx
        echo `which wx-config`
        wx-config --list
        wx-config --version
        wx-config --version-full
        wx-config --libs
    - name: Build
      run: |
        cd fractalstream-ui-wx
        cp stack.yaml.macos stack.yaml
        stack build
